title: "Henry's Blog"
description: "Math & Competitive Programming Notes"

# Use Just the Docs
remote_theme: just-the-docs/just-the-docs

# Required for GitHub Pages
plugins:
  - jekyll-remote-theme

url: "https://henriess.github.io"
baseurl: ""
just_the_docs:
  math: true
