title: "Math and Programming stuff"
description: "Math & Competitive Programming Notes"

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

url: "https://henriess.github.io"
baseurl: ""

just_the_docs:
  custom_js:
    - assets/js/custom.js
  math: true


